### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by vlhsmylv** [adrianhajdin/project_hoobank#18]
Hello,

The blue gradient in the Testimonials section overflows. Check the image below.

You can check the repo from there: [Github Repo](https://github.com/vlhsmylv/hoobank).

<img width="1440" alt="Screenshot 2023-08-23 at 21 01 33" src="https://github.com/adrianhajdin/project_hoobank/assets/101264220/6b6b5707-b22a-4d39-8d85-bde736a29e76">

**Comment by Abdul-Moiz-Iqbal** [comment]
Hi there,
Can I work on it?

**Comment by vlhsmylv** [comment]
> Hi there,
> 
> Can I work on it?
> 
> 

Sure! I will appreciate it :)

**Comment by Abdul-Moiz-Iqbal** [comment]
I think this issue is fixed? 
If so is there any other issue where I can help you?

**Comment by vlhsmylv** [comment]
> I think this issue is fixed? 
> 
> If so is there any other issue where I can help you?

Actually, not solved. I just removed that part for now. I will add again ASAP.

**Comment by Abdul-Moiz-Iqbal** [comment]
Ok, I will be waiting for it.

**Comment by vlhsmylv** [comment]
> Ok, I will be waiting for it.

Done!

**Comment by Abdul-Moiz-Iqbal** [comment]
Hi there!
I am really sorry I wasn't available last week.
I have fixed the issue.
Where should I send pull request now? In this repositary I am seeing something else now
